
name: ci
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Make sh executable'
        run: |
          chmod +x run.sh
          chmod +x build.sh
          chmod +x test.sh
      - name: 'Execute tests'
        run: ./test.sh ci_logs.txt
      - name: 'Save log in env'
        run: |
          echo "LOG="$(cat ci_logs.txt)"" >> $GITHUB_ENV
      - name: Checkout logs
        uses: actions/checkout@v2
        with:
          ref: 'logs'
      - name: 'Append test to log'
        run: |
          echo -e "${{ env.LOG }}" | sed -e "s/ test/\\ntest/g" >> ci_logs.txt  
      - name: 'Commit tests'
        uses: EndBug/add-and-commit@v7
        with:
          add: 'ci_logs.txt'
          message: 'Auto test'
          default_author: github_actions
          branch: 'logs'
